class config(object):
	
	def __init__(self):
		self.keyboard_options = { 'q': quit }
		self.audio_channel = {
			"crowd": pygame.mixer.Channel(1),
			"ding": pygame.mixer.Channel(2),
			"firstBlood": pygame.mixer.Channel(3),
			"dominating": pygame.mixer.Channel(3),
			"unstoppable": pygame.mixer.Channel(3),
			"wickedSick": pygame.mixer.Channel(3),
			"triple": pygame.mixer.Channel(4),
			"super": pygame.mixer.Channel(4),
			"hyper": pygame.mixer.Channel(4),
			"brutal": pygame.mixer.Channel(4),
			"master": pygame.mixer.Channel(4),
			"awesome": pygame.mixer.Channel(4),
			"blaster": pygame.mixer.Channel(4),
			"monster": pygame.mixer.Channel(4),
			"comboBreaker": pygame.mixer.Channel(3),
			"excellent": pygame.mixer.Channel(3),
			"finishHim": pygame.mixer.Channel(3),
			"humiliation": pygame.mixer.Channel(3),
			"superb": pygame.mixer.Channel(3),
			"supremeVictory": pygame.mixer.Channel(3),
			"thatWasPathetic": pygame.mixer.Channel(3),
			"danger": pygame.mixer.Channel(2),
			"wellDone": pygame.mixer.Channel(3),
			"winner": pygame.mixer.Channel(3),
			"youllNeverWin": pygame.mixer.Channel(3),
			"victory": pygame.mixer.Channel(3)
		}
		self.audio = {
			"ding": pygame.mixer.Sound('sounds/ding.ogg'),
			"firstBlood": pygame.mixer.Sound('sounds/1-first-blood.ogg'),
			"dominating": pygame.mixer.Sound('sounds/2-dominating.ogg'),
			"unstoppable": pygame.mixer.Sound('sounds/unstoppable.ogg'),
			"wickedSick": pygame.mixer.Sound('sounds/whicked-sick.ogg'),
			"triple": pygame.mixer.Sound('sounds/3-triple.ogg'),
			"super": pygame.mixer.Sound('sounds/4-super.ogg'),
			"hyper": pygame.mixer.Sound('sounds/5-hyper.ogg'),
			"brutal": pygame.mixer.Sound('sounds/6-brutal.ogg'),
			"master": pygame.mixer.Sound('sounds/7-master.ogg'),
			"awesome": pygame.mixer.Sound('sounds/8-awesome.ogg'),
			"blaster": pygame.mixer.Sound('sounds/9-blaster.ogg'),
			"monster": pygame.mixer.Sound('sounds/10-monster.ogg'),
			"comboBreaker": pygame.mixer.Sound('sounds/combo-breaker.ogg'),
			"crowd": pygame.mixer.Sound('sounds/crowd.ogg'),
			"excellent": pygame.mixer.Sound('sounds/excellent.ogg'),
			"finishHim": pygame.mixer.Sound('sounds/finish-him.ogg'),
			"humiliation": pygame.mixer.Sound('sounds/humiliation.ogg'),
			"superb": pygame.mixer.Sound('sounds/superb.ogg'),
			"supremeVictory": pygame.mixer.Sound('sounds/supreme-victory.ogg'),
			"thatWasPathetic": pygame.mixer.Sound('sounds/that-was-pathetic.ogg'),
			"danger": pygame.mixer.Sound('sounds/danger.ogg'),
			"wellDone": pygame.mixer.Sound('sounds/well-done.ogg'),
			"winner": pygame.mixer.Sound('sounds/winner.ogg'),
			"youllNeverWin": pygame.mixer.Sound('sounds/youll-never-win.ogg'),
			"victory": pygame.mixer.Sound('sounds/victory.ogg')	
		}
