class config(object):
	
	def __init__(self):
		self.default_volume = 0.1
		self.audio_channel = {
			"crowd": 1,
			"ding": 2,
			"firstBlood": 3,
			"dominating": 3,
			"unstoppable": 3,
			"wickedSick": 3,
			"triple": 4,
			"super": 4,
			"hyper": 4,
			"brutal": 4,
			"master": 4,
			"awesome": 4,
			"blaster": 4,
			"monster": 4,
			"comboBreaker": 3,
			"excellent": 3,
			"finishHim": 3,
			"humiliation": 3,
			"superb": 3,
			"supremeVictory": 3,
			"thatWasPathetic": 3,
			"danger": 2,
			"wellDone": 3,
			"winner": 3,
			"youllNeverWin": 3,
			"victory": 3
		}
		self.audio = {
			"ding": 'sounds/ding.ogg',
			"firstBlood": 'sounds/1-first-blood.ogg',
			"dominating": 'sounds/2-dominating.ogg',
			"unstoppable": 'sounds/unstoppable.ogg',
			"wickedSick": 'sounds/whicked-sick.ogg',
			"triple": 'sounds/3-triple.ogg',
			"super": 'sounds/4-super.ogg',
			"hyper": 'sounds/5-hyper.ogg',
			"brutal": 'sounds/6-brutal.ogg',
			"master": 'sounds/7-master.ogg',
			"awesome": 'sounds/8-awesome.ogg',
			"blaster": 'sounds/9-blaster.ogg',
			"monster": 'sounds/10-monster.ogg',
			"comboBreaker": 'sounds/combo-breaker.ogg',
			"crowd": 'sounds/crowd.ogg',
			"excellent": 'sounds/excellent.ogg',
			"finishHim": 'sounds/finish-him.ogg',
			"humiliation": 'sounds/humiliation.ogg',
			"superb": 'sounds/superb.ogg',
			"supremeVictory": 'sounds/supreme-victory.ogg',
			"thatWasPathetic": 'sounds/that-was-pathetic.ogg',
			"danger": 'sounds/danger.ogg',
			"wellDone": 'sounds/well-done.ogg',
			"winner": 'sounds/winner.ogg',
			"youllNeverWin": 'sounds/youll-never-win.ogg',
			"victory": 'sounds/victory.ogg'	
		}
